(function(){var h={},mt={},c={id:"7ea6c0c8412eb91d6e44a2459dc4ae81",dm:["itheima.com"],js:"tongji.baidu.com/hm-web/js/",etrk:[],cetrk:[],cptrk:[],icon:'/hmt/icon/21|gif|20|20',ctrk:["%5b%22http%3a%5c%2f%5c%2fitheima.com%5c%2fsubject%5c%2fios%5c%2findex.html%3fwangmeng%3d*%22%2c%22http%3a%5c%2f%5c%2fitheima.com%5c%2fsubject%5c%2fnetwzgl%5c%2findex.shtml%3fwangmeng%3d*%22%2c%22http%3a%5c%2f%5c%2fitheima.com%5c%2fsubject%5c%2fsz%5c%2findex.shtml%3fwangmeng%3d*%22%2c%22http%3a%5c%2f%5c%2fitheima.com%5c%2fsubject%5c%2fjavazl%5c%2findex.shtml%3fjingjia%3d*%22%2c%22http%3a%5c%2f%5c%2fitheima.com%5c%2fsubject%5c%2fsecrets%5c%2findex.shtml%3fjingjia%3d*%22%5d"],nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,kbtrk:0,pt:0,spa:0,oc:0,aet:'',hca:'99C74F15EAA7595B',conv:0,med:0,cvcc:{q:/tencent:\/\/|qq\.(com|htm)|kefu|openkf|swt|zoos|53kf|doyoo|looyu|leyu|zixun|chat|talk|openQQ|open_ask|online/i},cvcf:['queryyy'],apps:''};var t=void 0,v=!0,w=null,x=!1;mt.cookie={};mt.cookie.set=function(a,b,d){var f;d.N&&(f=new Date,f.setTime(f.getTime()+d.N));document.cookie=a+"="+b+(d.domain?"; domain="+d.domain:"")+(d.path?"; path="+d.path:"")+(f?"; expires="+f.toGMTString():"")+(d.Mc?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:w};
mt.cookie.lc=function(a,b){try{var d="Hm_ck_"+ +new Date;mt.cookie.set(d,"is-cookie-enabled",{domain:a,path:b,N:t});var f="is-cookie-enabled"===mt.cookie.get(d)?"1":"0";mt.cookie.set(d,"",{domain:a,path:b,N:-1});return f}catch(e){return"0"}};mt.lang={};mt.lang.d=function(a,b){return"[object "+b+"]"==={}.toString.call(a)};mt.lang.Ya=function(a){return mt.lang.d(a,"Number")&&isFinite(a)};mt.lang.F=function(a){return mt.lang.d(a,"String")};mt.lang.isArray=function(a){return mt.lang.d(a,"Array")};
mt.lang.h=function(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a};mt.lang.trim=function(a){return a.replace(/^\s+|\s+$/g,"")};mt.lang.D=function(a,b){var d=x;if(a==w||!mt.lang.d(a,"Array")||b===t)return d;if(Array.prototype.indexOf)d=-1!==a.indexOf(b);else for(var f=0;f<a.length;f++)if(a[f]===b){d=v;break}return d};mt.url={};mt.url.m=function(a,b){var d=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return d?d[3]:w};
mt.url.Ic=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:w};mt.url.Pb=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):w};mt.url.S=function(a){return(a=mt.url.Pb(a))?a.replace(/:\d+$/,""):a};mt.url.Aa=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):w};
(function(){var a=mt.lang,b=mt.url;mt.g={};mt.g.Hb=function(d){return document.getElementById(d)};mt.g.ya=function(d){if(!d)return w;try{d=String(d);if(0===d.indexOf("!HMCQ!"))return d;if(0===d.indexOf("!HMCC!"))return document.querySelector(d.substring(6,d.length));for(var f=d.split(">"),e=document.body,a=f.length-1;0<=a;a--)if(-1<f[a].indexOf("#")){var b=f[a].split("#")[1];(e=document.getElementById(b))||(e=document.getElementById(decodeURIComponent(b)));f=f.splice(a+1,f.length-(a+1));break}for(d=
0;e&&d<f.length;){var l=String(f[d]).toLowerCase();if(!("html"===l||"body"===l)){var a=0,n=f[d].match(/\[(\d+)\]/i),b=[];if(n)a=n[1]-1,l=l.split("[")[0];else if(1!==e.childNodes.length){for(var s=0,r=0,m=e.childNodes.length;r<m;r++){var p=e.childNodes[r];1===p.nodeType&&p.nodeName.toLowerCase()===l&&s++;if(1<s)return w}if(1!==s)return w}for(s=0;s<e.childNodes.length;s++)1===e.childNodes[s].nodeType&&e.childNodes[s].nodeName.toLowerCase()===l&&b.push(e.childNodes[s]);if(!b[a])return w;e=b[a]}d++}return e}catch(k){return w}};
mt.g.Aa=function(a,f){var e=[],b=[];if(!a)return b;for(;a.parentNode!=w;){for(var g=0,l=0,n=a.parentNode.childNodes.length,s=0;s<n;s++){var r=a.parentNode.childNodes[s];if(r.nodeName===a.nodeName&&(g++,r===a&&(l=g),0<l&&1<g))break}if((n=""!==a.id)&&f){e.unshift("#"+encodeURIComponent(a.id));break}else n&&(n="#"+encodeURIComponent(a.id),n=0<e.length?n+">"+e.join(">"):n,b.push(n)),e.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+(1<g?"["+l+"]":""));a=a.parentNode}b.push(e.join(">"));return b};
mt.g.ha=function(a){return(a=mt.g.Aa(a,v))&&a.length?String(a[0]):""};mt.g.Sb=function(a){return mt.g.Aa(a,x)};mt.g.Ra=function(a){var f;for(f="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==f)return a;return w};mt.g.Lb=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.g.Sa=function(a){var f={top:0,left:0};if(!a)return f;var e=mt.g.Lb(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(f=a.getBoundingClientRect());return{top:f.top+(window.pageYOffset||e.scrollTop)-
(e.clientTop||0),left:f.left+(window.pageXOffset||e.scrollLeft)-(e.clientLeft||0)}};mt.g.getAttribute=function(a,f){var e=a.getAttribute&&a.getAttribute(f)||w;if(!e&&a.attributes&&a.attributes.length)for(var b=a.attributes,g=b.length,l=0;l<g;l++)b[l].nodeName===f&&(e=b[l].nodeValue);return e};mt.g.R=function(a){var f="document";a.tagName!==t&&(f=a.tagName);return f.toLowerCase()};mt.g.Wb=function(b){var f="";b.textContent?f=a.trim(b.textContent):b.innerText&&(f=a.trim(b.innerText));f&&(f=f.replace(/\s+/g,
" ").substring(0,255));return f};mt.g.Q=function(d,f){var e;a.F(d)&&0===String(d).indexOf("!HMCQ!")?(e=String(d),e=b.m(document.location.href,e.substring(6,e.length))):a.F(d)||(e=mt.g.R(d),"input"===e&&f&&("button"===d.type||"submit"===d.type)?e=a.trim(d.value)||"":"input"===e&&!f&&"password"!==d.type?e=a.trim(d.value)||"":"img"===e?(e=mt.g.getAttribute,e=e(d,"alt")||e(d,"title")||e(d,"src")):e="body"===e||"html"===e?["(hm-default-content-for-",e,")"].join(""):mt.g.Wb(d));return String(e||"").substring(0,
255)};(function(){(mt.g.qc=function(){function a(){if(!a.ka){a.ka=v;for(var f=0,e=b.length;f<e;f++)b[f]()}}function f(){try{document.documentElement.doScroll("left")}catch(e){setTimeout(f,1);return}a()}var e=x,b=[],g;document.addEventListener?g=function(){document.removeEventListener("DOMContentLoaded",g,x);a()}:document.attachEvent&&(g=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",g),a())});(function(){if(!e)if(e=v,"complete"===document.readyState)a.ka=v;
else if(document.addEventListener)document.addEventListener("DOMContentLoaded",g,x),window.addEventListener("load",a,x);else if(document.attachEvent){document.attachEvent("onreadystatechange",g);window.attachEvent("onload",a);var b=x;try{b=window.frameElement==w}catch(n){}document.documentElement.doScroll&&b&&f()}})();return function(f){a.ka?f():b.push(f)}}()).ka=x})();return mt.g})();mt.event={};
mt.event.e=function(a,b,d){a.attachEvent?a.attachEvent("on"+b,function(f){d.call(a,f)}):a.addEventListener&&a.addEventListener(b,d,x)};mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=x};
(function(){var a=mt.event;mt.f={};mt.f.Ea=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.f.Hc=function(){if(document.documentMode)return document.documentMode;var a=/msie (\d+\.\d+)/i.exec(navigator.userAgent);return a?+a[1]||0:0};mt.f.Jc=function(){try{return!!navigator.userAgent.match(/safari/i)&&!navigator.userAgent.match(/chrome/i)&&"undefined"!==typeof document.body.style.webkitFilter&&!window.chrome}catch(a){return x}};mt.f.cookieEnabled=navigator.cookieEnabled;mt.f.javaEnabled=navigator.javaEnabled();
mt.f.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.f.sc=(window.screen.width||0)+"x"+(window.screen.height||0);mt.f.colorDepth=window.screen.colorDepth||0;mt.f.Ub=function(){var a;a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.f.Va=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.f.C=
function(){return mt.f.Ub()+mt.f.Va()};mt.f.nb=0;mt.f.Yb=function(){var a=document;return parseInt(window.innerWidth||a.documentElement.clientWidth||a.body.offsetWidth||0,10)};mt.f.orientation=0;(function(){function b(){var a=0;window.orientation!==t&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==t)&&(a=screen.orientation.angle);mt.f.orientation=a;mt.f.nb=mt.f.Yb()}b();a.e(window,"orientationchange",b)})();return mt.f})();mt.G={};
mt.G.parse=function(a){return(new Function("return ("+a+")"))()};
mt.G.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var f=d[a];if(f)return f;f=a.charCodeAt();return"\\u00"+Math.floor(f/16).toString(16)+(f%16).toString(16)}));return'"'+a+'"'}function b(a){return 10>a?"0"+a:a}var d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(f){switch(typeof f){case "undefined":return"undefined";case "number":return isFinite(f)?String(f):"null";case "string":return a(f);case "boolean":return String(f);
default:if(f===w)return"null";if(f instanceof Array){var e=["["],d=f.length,g,l,n;for(l=0;l<d;l++)switch(n=f[l],typeof n){case "undefined":case "function":case "unknown":break;default:g&&e.push(","),e.push(mt.G.stringify(n)),g=1}e.push("]");return e.join("")}if(f instanceof Date)return'"'+f.getFullYear()+"-"+b(f.getMonth()+1)+"-"+b(f.getDate())+"T"+b(f.getHours())+":"+b(f.getMinutes())+":"+b(f.getSeconds())+'"';g=["{"];l=mt.G.stringify;for(d in f)if(Object.prototype.hasOwnProperty.call(f,d))switch(n=
f[d],typeof n){case "undefined":case "unknown":case "function":break;default:e&&g.push(","),e=1,g.push(l(d)+":"+l(n))}g.push("}");return g.join("")}}}();mt.localStorage={};mt.localStorage.ta=function(){if(!mt.localStorage.l)try{mt.localStorage.l=document.createElement("input"),mt.localStorage.l.type="hidden",mt.localStorage.l.style.display="none",mt.localStorage.l.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.l)}catch(a){return x}return v};
mt.localStorage.set=function(a,b,d){var f=new Date;f.setTime(f.getTime()+d||31536E6);try{window.localStorage?(b=f.getTime()+"|"+b,window.localStorage.setItem(a,b)):mt.localStorage.ta()&&(mt.localStorage.l.expires=f.toUTCString(),mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.setAttribute(a,b),mt.localStorage.l.save(document.location.hostname))}catch(e){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var b=a.indexOf("|"),d=a.substring(0,b)-0;if(d&&d>(new Date).getTime())return a.substring(b+1)}}else if(mt.localStorage.ta())try{return mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.getAttribute(a)}catch(f){}return w};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.ta())try{mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.removeAttribute(a),mt.localStorage.l.save(document.location.hostname)}catch(b){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,b){try{window.sessionStorage&&window.sessionStorage.setItem(a,b)}catch(d){}};
mt.sessionStorage.get=function(a){try{return window.sessionStorage?window.sessionStorage.getItem(a):w}catch(b){return w}};mt.sessionStorage.remove=function(a){try{window.sessionStorage&&window.sessionStorage.removeItem(a)}catch(b){}};mt.jb={};mt.jb.log=function(a,b){var d=new Image,f="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[f]=d;d.onload=function(){d.onload=w;d=window[f]=w;b&&b(a)};d.src=a};mt.lb={};
mt.lb.Xb=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];b&&b.description&&(a=b.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=b.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(d){}return a};
h.t={fc:"http://tongji.baidu.com/hm-web/welcome/ico",Ia:"hm.baidu.com/hm.gif",tb:/^(tongji|hmcdn).baidu.com$/,Bc:"tongji.baidu.com",bc:"hmmd",dc:"hmpl",Ec:"utm_medium",ac:"hmkw",Gc:"utm_term",Zb:"hmci",Dc:"utm_content",ec:"hmsr",Fc:"utm_source",$b:"hmcu",Cc:"utm_campaign",M:0,J:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",ma:"https:",Kc:0,yb:6E5,Lc:6E5,tc:5E3,zb:5,da:1024,xb:1,na:2147483647,mb:"hca kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn r ww p ct u tt".split(" "),
U:v,Oa:["a","input","button"],La:{id:"data-hm-id",ca:"data-hm-class",ba:"data-hm-xpath",content:"data-hm-content",qa:"data-hm-tag",link:"data-hm-link"},Na:"data-hm-enabled",Ma:"data-hm-disabled",nc:"https://hmcdn.baidu.com/static/tongji/plugins/",eb:["UrlChangeTracker","OcpcCbHm"]};(function(){var a={B:{},e:function(a,d){this.B[a]=this.B[a]||[];this.B[a].push(d)},K:function(a,d){this.B[a]=this.B[a]||[];for(var f=this.B[a].length,e=0;e<f;e++)this.B[a][e](d)}};return h.o=a})();
(function(){var a=mt.lang,b=/^https?:\/\//,d={Kb:function(a){var e;try{e=JSON.parse(decodeURIComponent(a[0]))}catch(b){}return e},Za:function(a,e){return d.$a(h.c&&h.c.b&&h.c.b.u,a,e)||d.$a(document.location.href,a,e)},$a:function(a,e,d){if(a===t)return x;b.test(e)||(a=a.replace(b,""));e=e.replace(/\/$/,"");a=a.replace(/\/$/,"");d&&(a=a.replace(/^(https?:\/\/)?www\./,"$1"));return RegExp("^"+e.replace(/[?.+^${}()|[\]\\]/g,"\\$&").replace(/\*/g,".*")+"$").test(a)},O:function(f,e){var b=d.Kb(f);if(!a.d(b,
"Undefined")){if(a.d(b,"Array")){for(var g=0;g<b.length;g++)if(d.Za(b[g],e))return v;return x}if(a.d(b,"Object")){var g=[],l;for(l in b)b.hasOwnProperty(l)&&d.Za(l,e)&&(g=g.concat(b[l]));return g}}}};return h.ea=d})();
(function(){function a(a,f){var e=document.createElement("script");e.charset="utf-8";b.d(f,"Function")&&(e.readyState?e.onreadystatechange=function(){if("loaded"===e.readyState||"complete"===e.readyState)e.onreadystatechange=w,f()}:e.onload=function(){f()});e.src=a;var u=document.getElementsByTagName("script")[0];u.parentNode.insertBefore(e,u)}var b=mt.lang;return h.load=a})();
(function(){var a=h.t,b={init:function(){if(""!==c.icon){var b=c.icon.split("|"),f=a.fc+"?s="+c.id,e="https://hmcdn.baidu.com/static"+b[0]+".gif";document.write("swf"===b[1]||"gif"===b[1]?'<a href="'+f+'" target="_blank"><img border="0" src="'+e+'" width="'+b[2]+'" height="'+b[3]+'"></a>':'<a href="'+f+'" target="_blank">'+b[0]+"</a>")}}};h.o.e("pv-b",b.init);return b})();
(function(){var a=mt.cookie,b=mt.localStorage,d=mt.sessionStorage,f={getData:function(e){try{return a.get(e)||d.get(e)||b.get(e)}catch(f){}},setData:function(e,u,g){try{a.set(e,u,{domain:f.P(),path:f.ga(),N:g}),g?b.set(e,u,g):d.set(e,u)}catch(l){}},removeData:function(e){try{a.set(e,"",{domain:f.P(),path:f.ga(),N:-1}),d.remove(e),b.remove(e)}catch(u){}},V:function(a,f){a="."+a.replace(/:\d+/,"");f="."+f.replace(/:\d+/,"");var b=a.indexOf(f);return-1<b&&b+f.length===a.length},la:function(a,f){a=a.replace(/^https?:\/\//,
"");return 0===a.indexOf(f)},P:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(f.V(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},ga:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&f.la(document.location.href,d))return d.replace(/^[^/]+(\/.*)/,"$1")+"/"}return"/"}};return h.wa=f})();
(function(){var a=mt.lang,b=mt.G,d=h.wa,f={pageview:{},session:{},autoEventTracking:{},customEvent:{},user:{}},e={user:1,session:2,pageview:3,autoEventTracking:3,customEvent:3,others:3},u=["session","user"],g="Hm_up_"+c.id,l={init:function(){l.ic()},ic:function(){try{var e=b.parse(decodeURIComponent(d.getData(g)));a.d(e,"Object")&&(f.user=e)}catch(s){}},w:function(a){var b={};f[a]!==t&&(b=f[a]);a=this.Ba();for(var e in b)b.hasOwnProperty(e)&&(a[e]=b[e]);return a},Ba:function(){for(var a={},b,e=u.length-
1;0<=e;e--){b=f[u[e]];for(var m in b)b.hasOwnProperty(m)&&(a[m]=b[m])}return a},setProperty:function(e,s,d){var m=f[e];if(a.d(m,"Object")&&a.d(s,"Object")){for(var p in s)if(s.hasOwnProperty(p)){var k=a.h(String(p));if(d||!/^_/.test(k)&&!/_$/.test(k)||/^(_iden|ei_|ec_|ex_|en_|et_|el_)$/.test(k)){var q=s[p];if(q==w)delete m[k];else{if(a.d(q,"Object")||a.d(q,"Array"))q=b.stringify(q);q=a.h(String(q));l.kc(e,k,q)&&(m[k]={value:q,scope:l.Ua(e)})}}}"user"===e&&l.Ga()}},n:function(b){b!==t&&("userId"===
b&&a.d(f.user,"Object")?(delete f.user.uid_,l.Ga()):"user"===b&&a.d(f.user,"Object")?(b=f.user.uid_,f.user=b===t?{}:{uid_:b},l.Ga()):f[b]!==t&&(f[b]={}))},Ga:function(){try{d.setData(g,encodeURIComponent(b.stringify(f.user)),c.age)}catch(a){}},kc:function(a,b,e){var m=v,d=f[a];if(256<encodeURIComponent(String(b)).length||256<encodeURIComponent(String(e)).length)m=x;else{var k=d[b];d[b]={value:e,scope:l.Ua(a)};a=l.I(l.w(a));2048<encodeURIComponent(a).length&&(k!==t?d[b]=k:delete d[b],m=x)}return m},
I:function(a){var b=[],f,e;for(e in a)a.hasOwnProperty(e)&&(f=[e,a[e].value],(1===a[e].scope||2===a[e].scope)&&f.push(a[e].scope),b.push(f.join("*")));return b.join("!")},Ua:function(a){a=e[a];return a!==t?a:e.others}};return h.L=l})();
(function(){var a=mt.g,b=mt.lang,d=h.o,f=h.ea,e=h.L,u=e.I;if(b.isArray(c.cptrk)&&0<c.cptrk.length){var g={cb:{},ra:{},init:function(){for(var a,e=f.O(c.cptrk)||[],d=0;d<e.length;d++)if(a=e[d],a.a!==t&&b.d(a.a,"Object")){a=a.a;for(var r in a)a.hasOwnProperty(r)&&(g.ra[r]=String(a[r]))}},bb:function(){var b,e,f;for(f in g.ra)if(g.ra.hasOwnProperty(f)&&g.cb[f]===t&&(b=g.ra[f],b=a.ya(b)))e=e===t?{}:e,e[f]=a.Q(b,x),g.cb[f]=v;return e},Ca:function(){var a=g.bb();a&&g.vc(a)},hc:function(){"MutationObserver"in
window&&document.body?(new MutationObserver(g.Ca)).observe(document.body,{childList:v,subtree:v}):window.setInterval(g.Ca,15E3)},vc:function(a){if(b.d(a,"Object")){e.setProperty("pageview",a);a=h.c.b.p;var f=h.c.b.ep;h.c.b.et=9;h.c.b.ep="";h.c.b.p=u(e.w("pageview"));h.c.j();h.c.b.p=a;h.c.b.ep=f;e.n("pageview")}}};g.init();d.e("pv-b",function(){var a=g.bb();a&&e.setProperty("pageview",a)});g.hc();a.qc(g.Ca)}})();
(function(){var a=mt.lang,b=mt.g,d=h.ea,f={fa:function(a,u){return function(g){var l=g.target||g.srcElement;if(l){var n=d.O(u)||[],s=l.getAttribute(a.sa);g=g.clientX+":"+g.clientY;if(s&&s===g)l.removeAttribute(a.sa);else if(0<n.length&&(l=b.Sb(l))&&l.length)if(n=l.length,s=l[l.length-1],1E4>n*s.split(">").length)for(s=0;s<n;s++)f.ib(a,l[s]);else f.ib(a,s)}}},ib:function(b,f){for(var d={},l=String(f).split(">").length,n=0;n<l;n++)d[f]="",f=f.substring(0,f.lastIndexOf(">"));b&&(a.d(b,"Object")&&b.Pa)&&
b.Pa(d)},rc:function(a,b){return function(f){(f.target||f.srcElement).setAttribute(a.sa,f.clientX+":"+f.clientY);a&&a.s&&(b?a.s(b):a.s("#"+encodeURIComponent(this.id),f.type))}}};return h.Db=f})();
(function(){var a=mt.g,b=mt.event,d=mt.lang,f=h.t,e=h.ea,u=h.Db,g=h.L,l=g.I,n={sa:"HM_ce",pb:function(){if(c.cetrk&&0<c.cetrk.length){b.e(document,"click",u.fa(n,c.cetrk));for(var f=e.O(c.cetrk)||[],d=0,m=f.length;d<m;d++){var p=f[d],k=p.p||"";-1===k.indexOf(">")&&(0===k.indexOf("#")&&(k=k.substring(1)),(k=a.Hb(k))&&b.e(k,"click",u.rc(n,p)))}}},Pa:function(a){for(var b=e.O(c.cetrk)||[],f=0;f<b.length;f++){var d=b[f],k=n.Nb(d.p,a);k&&n.s(d,k)}},Nb:function(a,b){a=String(a);if(0<a.indexOf("*")){var f=
RegExp("^"+a.replace(/\[/g,"\\[").replace(/\]/g,"\\]").replace(/\*/,"\\d+")+"$"),e;for(e in b)if(b.hasOwnProperty(e)&&f.test(e))return e;return w}return b.hasOwnProperty(a)?a:w},s:function(b,f){h.c.b.et=7;var e=b&&b.k||"",e=d.h(e),p={};if(b&&b.a&&d.d(b.a,"Object")){var k=b.a,q;for(q in k)if(k.hasOwnProperty(q)){var y=n.Tb(k[q]||"",f),y=y?a.Q(y,x):"";p[q]=y}}p=n.Ib(p,f||b&&b.p);p._iden=e;g.setProperty("customEvent",p);h.c.b.ep="";h.c.b.p=l(g.w("customEvent"));h.c.j();h.c.b.p="";g.n("customEvent")},
Ib:function(b,e){var d=a.ya(e),p=f.La;d&&(c.aet&&c.aet.length?(b.ei_=a.getAttribute(d,p.id)||a.getAttribute(d,"id")||"",b.ec_=a.getAttribute(d,p.ca)||a.getAttribute(d,"class")||"",b.ex_=a.getAttribute(d,p.ba)||a.ha(d),b.en_=a.getAttribute(d,p.content)||a.Q(d,v),b.et_=a.getAttribute(d,p.qa)||a.R(d),b.el_=a.getAttribute(d,p.link)||a.getAttribute(d,"href")||""):(b.ex_=a.getAttribute(d,p.ba)||a.ha(d),b.en_=a.getAttribute(d,p.content)||a.Q(d,v)));return b},Tb:function(b,f){b=String(b);f=String(f);if(0<
b.indexOf("*")){var e=/.*\[(\d+)\]$/.exec(f);b=b.replace("*",e?e[1]:"1")}return a.ya(b)}};h.o.e("pv-b",n.pb);return n})();
(function(){var a=mt.g,b=mt.lang,d=mt.event,f=mt.f,e=h.t,u=h.ea,g=[],l={ob:function(){c.ctrk&&0<c.ctrk.length&&(d.e(document,"mouseup",l.wb()),d.e(window,"unload",function(){l.oa()}),setInterval(function(){l.oa()},e.yb))},wb:function(){return function(a){if(u.O(c.ctrk,v)&&(a=l.Jb(a),""!==a)){var b=(e.ma+"//"+e.Ia+"?"+h.c.hb().replace(/ep=[^&]*/,"ep="+encodeURIComponent(a))).length;b+(e.na+"").length>e.da||(b+encodeURIComponent(g.join("!")+(g.length?"!":"")).length+(e.na+"").length>e.da&&l.oa(),g.push(a),
(g.length>=e.zb||/\*a\*/.test(a))&&l.oa())}}},Jb:function(d){var g=d.target||d.srcElement;if(0===e.xb){var r=(g.tagName||"").toLowerCase();if("embed"==r||"object"==r)return""}var m;f.Ea?(m=Math.max(document.documentElement.scrollTop,document.body.scrollTop),r=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),r=d.clientX+r,m=d.clientY+m):(r=d.pageX,m=d.pageY);d=l.Qb(d,g,r,m);var p=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:r-=
p/2;break;case 2:r-=p}p=[];p.push(r);p.push(m);p.push(d.Y);p.push(d.Z);p.push(d.pc);p.push(b.h(d.mc));p.push(d.aa);p.push(d.T);(g="a"===(g.tagName||"").toLowerCase()?g:a.Ra(g))?(p.push("a"),p.push(b.h(encodeURIComponent(g.href)))):p.push("b");return p.join("*")},Qb:function(e,d,g,m){e=a.ha(d);var p=0,k=0,q=0,y=0;if(d&&(p=d.offsetWidth||d.clientWidth,k=d.offsetHeight||d.clientHeight,y=a.Sa(d),q=y.left,y=y.top,b.d(d.getBBox,"Function")&&(k=d.getBBox(),p=k.width,k=k.height),"html"===(d.tagName||"").toLowerCase()))p=
Math.max(p,d.clientWidth),k=Math.max(k,d.clientHeight);return{Y:Math.round(100*((g-q)/p)),Z:Math.round(100*((m-y)/k)),pc:f.orientation,mc:e,aa:p,T:k}},oa:function(){0!==g.length&&(h.c.b.et=2,h.c.b.ep=g.join("!"),h.c.j(),g=[])}};h.o.e("pv-b",l.ob);return l})();
(function(){var a=mt.lang,b=mt.g,d=mt.event,f=mt.f,e=h.t,u=h.o,g=h.L,l=g.I,n=+new Date,s=[],r={fa:function(){return function(f){if(h.c&&h.c.U&&c.aet&&c.aet.length){var d=f.target||f.srcElement;if(d){var k=h.c.Oa,q=b.getAttribute(d,e.Na)!=w?v:x;if(b.getAttribute(d,e.Ma)==w)if(q)r.ua(r.za(d,f));else{var g=b.R(d);if(a.D(k,"*")||a.D(k,g))r.ua(r.za(d,f));else for(;d.parentNode!=w;){var q=d.parentNode,g=b.R(q),z="a"===g&&a.D(k,"a")?v:x,g="button"===g&&a.D(k,"button")?v:x,A=b.getAttribute(q,e.Na)!=w?v:x;
if(b.getAttribute(q,e.Ma)==w&&(z||g||A)){r.ua(r.za(q,f));break}d=d.parentNode}}}}}},za:function(d,g){var k={},q=e.La;k.id=b.getAttribute(d,q.id)||b.getAttribute(d,"id")||"";k.ca=b.getAttribute(d,q.ca)||b.getAttribute(d,"class")||"";k.ba=b.getAttribute(d,q.ba)||b.ha(d);k.content=b.getAttribute(d,q.content)||b.Q(d,v);k.qa=b.getAttribute(d,q.qa)||b.R(d);k.link=b.getAttribute(d,q.link)||b.getAttribute(d,"href")||"";k.type=g.type||"click";q=a.Ya(d.offsetTop)?d.offsetTop:0;"click"===g.type?q=f.Ea?g.clientY+
Math.max(document.documentElement.scrollTop,document.body.scrollTop):g.pageY:"touchend"===g.type&&(g.ab&&g.ab.changedTouches)&&(q=g.ab.changedTouches[0].pageY);k.Ac=q;q=this.Mb(g);k.Y=q.Y||0;k.Z=q.Z||0;k.aa=q.aa||0;k.T=q.T||0;k.Ja=q.Ja||"b";return k},Mb:function(d){var e=d.target||d.srcElement,k;if(f.Ea){var q=Math.max(document.documentElement.scrollTop,document.body.scrollTop);k=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft);k=d.clientX+k;d=d.clientY+q}else k=d.pageX,d=d.pageY;
var g=q=0,z=0,A=0;if(e&&(q=e.offsetWidth||e.clientWidth,g=e.offsetHeight||e.clientHeight,A=b.Sa(e),z=A.left,A=A.top,a.d(e.getBBox,"Function")&&(g=e.getBBox(),q=g.width,g=g.height),"html"===(e.tagName||"").toLowerCase()))q=Math.max(q,e.clientWidth),g=Math.max(g,e.clientHeight);return{Y:Math.round(100*((k-z)/q)),Z:Math.round(100*((d-A)/g)),aa:q,T:g,Ja:("a"===(e.tagName||"").toLowerCase()?e:b.Ra(e))?"a":"b"}},ua:function(b){var f=a.h;b=[+new Date-(h.c.W!==t?h.c.W:n),f(b.id),f(b.ca),f(b.qa),f(b.ba),f(b.link),
f(b.content),b.type,b.Ac,b.Y,b.Z,b.aa,b.T,b.Ja].join("*");r.va(b);a.d(this.$(),"Function")&&this.$()()},va:function(a){var b=e.da;a.length>b||(encodeURIComponent(s.join("!")+a).length>b&&0<s.length&&(r.s(s.join("!")),s=[]),s.push(a))},s:function(a){h.c.b.et=5;h.c.b.ep=a;g.setProperty("autoEventTracking",{view_h_:f.C()},v);h.c.b.p=l(g.w("autoEventTracking"));h.c.j();h.c.b.p="";g.setProperty("autoEventTracking",{view_h_:w},v)},$:function(){return function(){s&&s.length&&(r.s(s.join("!")),s=[])}}};a.F(c.aet)&&
""!==c.aet&&u.e("pv-b",function(){d.e(document,"click",r.fa());"ontouchend"in document&&d.e(window,"touchend",r.fa());d.e(window,"unload",r.$())});return r})();
(function(){var a=mt.lang,b=mt.event,d=mt.f,f=h.t,e=h.o,u=h.L,g=u.I,l=+new Date,n=[],s=w,r={rb:function(){a.F(c.aet)&&""!==c.aet&&setInterval(r.gb,f.tc)},gb:function(){var a=d.C();0<a-h.c.b.vl&&(h.c.b.vl=a)}},m={Cb:function(){return function(){h.c&&(h.c.U&&c.aet&&c.aet.length)&&(window.clearTimeout(s),s=window.setTimeout(function(){m.qb(d.C())},150))}},qb:function(a){m.va([+new Date-(h.c.W!==t?h.c.W:l),a].join("*"))},va:function(a){if(encodeURIComponent(n.join("!")+a).length>f.da||3<n.length)m.s(n.join("!")),
n=[];n.push(a)},s:function(a){r.gb();h.c.b.et=6;h.c.b.vh=d.Va();h.c.b.ep=a;u.setProperty("autoEventTracking",{view_h_:d.C()},v);h.c.b.p=g(u.w("autoEventTracking"));h.c.j();h.c.b.p="";u.setProperty("autoEventTracking",{view_h_:w},v)},$:function(){return function(){n&&n.length&&(m.s(n.join("!")),n=[])}}};a.F(c.aet)&&""!==c.aet&&e.e("pv-b",function(){b.e(window,"scroll",m.Cb());b.e(window,"unload",m.$());r.rb()});return m})();
(function(){function a(){return function(){h.c.b.nv=0;h.c.b.st=4;h.c.b.et=3;h.c.b.ep=h.xa.Rb()+","+h.xa.Ob();h.c.b.hca=c.hca;h.c.j()}}function b(){clearTimeout(z);var a;q&&(a="visible"==document[q]);y&&(a=!document[y]);l="undefined"==typeof a?v:a;if((!g||!n)&&l&&s)k=v,m=+new Date;else if(g&&n&&(!l||!s))k=x,p+=+new Date-m;g=l;n=s;z=setTimeout(b,100)}function d(a){var b=document,q="";if(a in b)q=a;else for(var f=["webkit","ms","moz","o"],d=0;d<f.length;d++){var e=f[d]+a.charAt(0).toUpperCase()+a.slice(1);
if(e in b){q=e;break}}return q}function f(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))s="focus"==a.type||"focusin"==a.type?v:x,b()}var e=mt.event,u=h.o,g=v,l=v,n=v,s=v,r=+new Date,m=r,p=0,k=v,q=d("visibilityState"),y=d("hidden"),z;b();(function(){var a=q.replace(/[vV]isibilityState/,"visibilitychange");e.e(document,a,b);e.e(window,"pageshow",b);e.e(window,"pagehide",b);"object"==typeof document.onfocusin?(e.e(document,"focusin",f),e.e(document,"focusout",f)):(e.e(window,
"focus",f),e.e(window,"blur",f))})();h.xa={Rb:function(){return+new Date-r},Ob:function(){return k?+new Date-m+p:p}};u.e("pv-b",function(){e.e(window,"unload",a())});u.e("duration-send",a());u.e("duration-done",function(){m=r=+new Date;p=0});return h.xa})();
(function(){var a=mt.lang,b=h.t,d=h.load,f={gc:function(f){if((window._dxt===t||a.d(window._dxt,"Array"))&&"undefined"!==typeof h.c){var u=h.c.P();d([b.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(u)].join(""),f)}},zc:function(b){if(a.d(b,"String")||a.d(b,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",b])}};return h.Ab=f})();
(function(){function a(a,b,f,d){if(!(a===t||b===t||d===t)){if(""===a)return[b,f,d].join("*");a=String(a).split("!");for(var e,k=x,g=0;g<a.length;g++)if(e=a[g].split("*"),String(b)===e[0]){e[1]=f;e[2]=d;a[g]=e.join("*");k=v;break}k||a.push([b,f,d].join("*"));return a.join("!")}}function b(a){for(var d in a)if({}.hasOwnProperty.call(a,d)){var e=a[d];f.d(e,"Object")||f.d(e,"Array")?b(e):a[d]=String(e)}}var d=mt.url,f=mt.lang,e=mt.G,u=mt.f,g=h.t,l=h.o,n=h.Ab,s=h.load,r=h.wa,m=h.L,p=m.I,k={X:[],pa:0,Fa:x,
A:{Ka:"",page:""},init:function(){k.i=0;m.init();l.e("pv-b",function(){k.Bb();k.Eb()});l.e("pv-d",function(){k.Fb();k.A.page=""});l.e("stag-b",function(){h.c.b.api=k.i||k.pa?k.i+"_"+k.pa:"";h.c.b.ct=[decodeURIComponent(r.getData("Hm_ct_"+c.id)||""),k.A.Ka,k.A.page].join("!")});l.e("stag-d",function(){h.c.b.api=0;k.i=0;k.pa=0})},Bb:function(){var a=window._hmt||[];if(!a||f.d(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,b=0;b<arguments.length;b++){var d=arguments[b];
f.d(d,"Array")&&(a.cmd[a.id].push(d),"_setAccount"===d[0]&&(1<d.length&&/^[0-9a-f]{31,32}$/.test(d[1]))&&(d=d[1],a.id=d,a.cmd[d]=a.cmd[d]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},Eb:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order)$/,f=0,e=b.length;f<e;f++){var g=b[f];d.test(g[0])?k.X.push(g):k.Ha(g)}a.cmd[c.id]={push:k.Ha}},Fb:function(){if(0<k.X.length)for(var a=0,b=k.X.length;a<b;a++)k.Ha(k.X[a]);k.X=w},Ha:function(a){var b=
a[0];if(k.hasOwnProperty(b)&&f.d(k[b],"Function"))k[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{31,32}$/.test(a[1])&&(k.i|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],x===a||v===a))k.i|=2,h.c.Wa=a},_trackPageview:function(a){1<a.length&&(a[1].charAt&&"/"===a[1].charAt(0))&&(k.i|=4,h.c.b.sn=h.c.Ta(),h.c.b.et=0,h.c.b.ep="",h.c.b.vl=u.C(),h.c.b.kb=0,h.c.Da?(h.c.b.nv=0,h.c.b.st=4):h.c.Da=v,k.Fa||(h.c.b.su=h.c.b.u||document.location.href),h.c.b.u=g.protocol+"//"+document.location.host+
a[1],h.c.b.p=p(m.w("pageview")),h.c.j(),h.c.b.p="",h.c.W=+new Date,m.n("pageview"))},_trackEvent:function(a){2<a.length&&(k.i|=8,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=4,h.c.b.ep=f.h(a[1])+"*"+f.h(a[2])+(a[3]?"*"+f.h(a[3]):"")+(a[4]?"*"+f.h(a[4]):""),h.c.b.p=p(m.Ba()),h.c.j(),h.c.b.p="")},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],d=a[4]||3;if(0<b&&6>b&&0<d&&4>d){k.pa++;for(var e=(h.c.b.cv||"*").split("!"),g=e.length;g<b-1;g++)e.push("*");e[b-1]=d+"*"+f.h(a[2])+"*"+f.h(a[3]);h.c.b.cv=e.join("!");
a=h.c.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?r.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):r.removeData("Hm_cv_"+c.id)}}},_setUserTag:function(b){if(!(3>b.length)){var d=f.h(b[1]);b=f.h(b[2]);if(d!==t&&b!==t){var e=decodeURIComponent(r.getData("Hm_ct_"+c.id)||""),e=a(e,d,1,b);r.setData("Hm_ct_"+c.id,encodeURIComponent(e),c.age)}}},_setVisitTag:function(b){if(!(3>b.length)){var d=f.h(b[1]);b=f.h(b[2]);if(d!==t&&b!==t){var e=k.A.Ka,e=a(e,d,2,b);k.A.Ka=e}}},_setPageTag:function(b){if(!(3>
b.length)){var d=f.h(b[1]);b=f.h(b[2]);if(d!==t&&b!==t){var e=k.A.page,e=a(e,d,3,b);k.A.page=e}}},_setReferrerOverride:function(a){1<a.length&&(a=a[1],f.d(a,"String")?(h.c.b.su="/"===a.charAt(0)?g.protocol+"//"+window.location.host+a:a,k.Fa=v):k.Fa=x)},_trackOrder:function(a){a=a[1];f.d(a,"Object")&&(b(a),k.i|=16,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=94,h.c.b.ep=e.stringify(a),h.c.b.p=p(m.Ba()),h.c.j(),h.c.b.p="")},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])k.i|=
32,h.c.b.et=93,h.c.b.ep=a,h.c.j()},_setDataxId:function(a){a=a[1];n.gc();n.zc(a)},_setUserId:function(a){a=a[1];if(a!==t&&(f.F(a)||f.Ya(a))){var b=m.w("user").uid_;if(!(b&&b.value===f.h(String(a)))){var b=h.c.b.p,d=h.c.b.ep;h.c.b.et=8;h.c.b.ep="";h.c.b.p="uid_*"+f.h(String(a));h.c.j();var e={};e.uid_=a;m.setProperty("user",e,v);h.c.b.p=b;h.c.b.ep=d}}},_clearUserId:function(a){1<a.length&&v===a[1]&&m.n("userId")},_setUserProperty:function(a){a=a[1];f.d(a,"Object")&&m.setProperty("user",a)},_clearUserProperty:function(a){1<
a.length&&v===a[1]&&m.n("user")},_setSessionProperty:function(a){a=a[1];f.d(a,"Object")&&m.setProperty("session",a)},_clearSessionProperty:function(a){1<a.length&&v===a[1]&&m.n("session")},_setPageviewProperty:function(a){a=a[1];f.d(a,"Object")&&m.setProperty("pageview",a)},_clearPageviewProperty:function(a){1<a.length&&v===a[1]&&m.n("pageview")},_setAutoEventTrackingProperty:function(a){a=a[1];f.d(a,"Object")&&m.setProperty("autoEventTracking",a)},_clearAutoEventTrackingProperty:function(a){1<a.length&&
v===a[1]&&m.n("autoEventTracking")},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],x===a||v===a))h.c.Xa=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],x===a||v===a))h.c.U=a},_trackPageDuration:function(a){1<a.length?(a=a[1],2===String(a).split(",").length&&(h.c.b.et=3,h.c.b.ep=a,h.c.j())):l.K("duration-send");l.K("duration-done")},_require:function(a){1<a.length&&(a=a[1],g.tb.test(d.S(a))&&s(a))},_providePlugin:function(a){if(1<a.length){var b=window._hmt,d=a[1];a=a[2];if(f.D(g.eb,
d)&&f.d(a,"Function")&&(b.plugins=b.plugins||{},b.H=b.H||{},b.plugins[d]=a,b.z=b.z||[],a=b.z.slice(),d&&a.length&&a[0][1]===d))for(var e=0,k=a.length;e<k;e++){var l=a[e][2]||{};if(b.plugins[d]&&!b.H[d])b.H[d]=new b.plugins[d](l),b.z.shift();else break}}},_requirePlugin:function(a){if(1<a.length){var b=window._hmt,d=a[1],e=a[2]||{};if(f.D(g.eb,d))if(b.plugins=b.plugins||{},b.H=b.H||{},b.plugins[d]&&!b.H[d])b.H[d]=new b.plugins[d](e);else{b.z=b.z||[];for(var e=0,l=b.z.length;e<l;e++)if(b.z[e][1]===
d)return;b.z.push(a);k._require([w,g.nc+d+".js"])}}},_trackCustomEvent:function(a){if(1<a.length){var b=a[1];a=a[2];f.d(a,"Object")||(a={});a._iden=b;m.setProperty("customEvent",a);h.c.b.et=7;h.c.b.ep="";h.c.b.p=p(m.w("customEvent"));h.c.j();h.c.b.p="";m.n("customEvent")}}};k.init();h.ub=k;return h.ub})();
(function(){var a=h.o;c.spa!==t&&"1"===String(c.spa)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","UrlChangeTracker"]),a.e("pv-b",function(){""!==window.location.hash&&(h.c.b.u=window.location.href)}))})();
(function(){function a(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=v,this.b={},this.Xa=this.Wa=v,this.U=k.U,this.Oa=e.F(c.aet)&&0<c.aet.length?c.aet.split(","):"",this.Da=x,this.init())}var b=mt.url,d=mt.jb,f=mt.lb,e=mt.lang,u=mt.cookie,g=mt.f,l=mt.sessionStorage,n=mt.G,s=mt.event,r=h.wa,m=h.L,p=m.I,k=h.t,q=h.load,y=h.o;a.prototype={V:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},la:function(a,
b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},ia:function(a){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(this.la(a,c.dm[d]))return v}else{var e=b.S(a);if(e&&this.V(e,c.dm[d]))return v}return x},P:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.V(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},ga:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.la(document.location.href,d))return d.replace(/^[^/]+(\/.*)/,
"$1")+"/"}return"/"},Vb:function(){if(!document.referrer)return k.J-k.M>c.vdur?1:4;var a=x;this.ia(document.referrer)&&this.ia(document.location.href)?a=v:(a=b.S(document.referrer),a=this.V(a||"",document.location.hostname));return a?k.J-k.M>c.vdur?1:4:3},xc:function(){var a,b,d,e,f,g;k.M=r.getData("Hm_lpvt_"+c.id)||0;13===k.M.length&&(k.M=Math.round(k.M/1E3));b=this.Vb();a=4!==b?1:0;if(g=r.getData("Hm_lvt_"+c.id)){e=g.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/
1E3));for(;2592E3<k.J-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(k.J);4<e.length;)e.shift();g=e.join(",");e=e[e.length-1]}else g=k.J,e="",f=1;this.jc()?(r.setData("Hm_lvt_"+c.id,g,c.age),r.setData("Hm_lpvt_"+c.id,k.J),d=u.lc(this.P(),this.ga())):this.Gb();if(0===c.nv&&this.ia(document.location.href)&&(""===document.referrer||this.ia(document.referrer)))a=0,b=4;this.b.nv=a;this.b.st=b;this.b.cc=d;this.b.lt=e;this.b.lv=f},jc:function(){var a=b.S(document.location.href);return!e.D("sjh.baidu.com isite.baidu.com ls.wejianzhan.com bs.wejianzhan.com product.weijianzhan.com qianhu.weijianzhan.com aisite.wejianzhan.com".split(" "),
a)},Gb:function(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){var d=a[b].split("=");d.length&&/Hm_(up|ct|cv|lp?vt)_[0-9a-f]{31}/.test(String(d[0]))&&r.removeData(d[0]);d.length&&/Hm_ck_[0-9]{13}/.test(String(d[0]))&&r.removeData(d[0])}},hb:function(){for(var a=[],b=this.b.et,d=0,e=k.mb.length;d<e;d++){var f=k.mb[d],g=this.b[f];"undefined"!==typeof g&&""!==g&&("tt"!==f||"tt"===f&&0===b)&&("ct"!==f||"ct"===f&&0===b)&&a.push(f+"="+encodeURIComponent(g))}return a.join("&")},yc:function(){this.xc();
this.b.si=c.id;this.b.sn=this.Ta();this.b.su=document.referrer;this.b.ds=g.sc;this.b.cl=g.colorDepth+"-bit";this.b.ln=String(g.language).toLowerCase();this.b.ja=g.javaEnabled?1:0;this.b.ck=g.cookieEnabled?1:0;this.b.lo="number"===typeof _bdhm_top?1:0;this.b.fl=f.Xb();this.b.v="1.2.88";this.b.cv=decodeURIComponent(r.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=g.C();var a=document.location.href;this.b.cm=b.m(a,k.bc)||"";this.b.cp=b.m(a,k.dc)||b.m(a,k.Ec)||"";this.b.cw=b.m(a,k.ac)||
b.m(a,k.Gc)||"";this.b.ci=b.m(a,k.Zb)||b.m(a,k.Dc)||"";this.b.cf=b.m(a,k.ec)||b.m(a,k.Fc)||"";this.b.cu=b.m(a,k.$b)||b.m(a,k.Cc)||"";/https?:/.test(document.location.protocol)&&(this.b.u=a)},init:function(){try{this.yc(),0===this.b.nv?this.wc():this.Qa(),h.c=this,this.vb(),y.K("pv-b"),this.uc()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));d.log(k.ma+"//"+k.Ia+"?"+b.join("&"))}},
uc:function(){function a(){y.K("pv-d")}this.Wa?(this.Da=v,this.b.et=0,this.b.ep="",this.b.p=p(m.w("pageview")),this.b.vl=g.C(),this.j(a),this.b.p=""):a();this.W=+new Date;m.n("pageview")},j:function(a){if(this.Xa){var b=this;b.b.rnd=Math.round(Math.random()*k.na);b.b.r=g.orientation;b.b.ww=g.nb;y.K("stag-b");var f=k.ma+"//"+k.Ia+"?"+b.hb();y.K("stag-d");b.sb(f);d.log(f,function(d){b.fb(d);e.d(a,"Function")&&a.call(b)})}},vb:function(){try{if(window.postMessage&&window.self!==window.parent){var a=
this;s.e(window,"message",function(d){if(b.S(d.origin)===k.Bc){d=d.data||{};var e=d.jn||"",f=/^customevent$|^heatmap$|^pageclick$|^select$/.test(e);if(RegExp(c.id).test(d.sd||"")&&f)a.b.rnd=Math.round(Math.random()*k.na),q(k.protocol+"//"+c.js+e+".js?"+a.b.rnd)}});window.parent.postMessage({id:c.id,url:document.location.href,status:"__Messenger__hmLoaded"},"*")}}catch(d){}},sb:function(a){var b;try{b=n.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}var e=this.b.u?"":"&u="+encodeURIComponent(document.location.href);
b.push(a.replace(/^https?:\/\//,"")+e);l.set("Hm_unsent_"+c.id,n.stringify(b))},fb:function(a){var b;try{b=n.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length){a=a.replace(/^https?:\/\//,"");for(var e=0;e<b.length;e++)if(a.replace(/&u=[^&]*/,"")===b[e].replace(/&u=[^&]*/,"")){b.splice(e,1);break}b.length?l.set("Hm_unsent_"+c.id,n.stringify(b)):this.Qa()}},Qa:function(){l.remove("Hm_unsent_"+c.id)},wc:function(){var a=this,b;try{b=n.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(e){b=[]}if(b.length)for(var f=
function(b){d.log(k.ma+"//"+b,function(b){a.fb(b)})},g=0;g<b.length;g++)f(b[g])},Ta:function(){return Math.round(+new Date/1E3)%65535}};return new a})();var B=h.t,C=h.load;c.pt&&C([B.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));})();
